version: "2"
run:
  tests: true
linters:
  enable:
    - dupl
    - gocyclo
  settings:
    dupl:
      threshold: 100
    gocyclo:
      min-complexity: 10
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - dupl
        text: generated
    paths:
      - .*_test.go
      - dist
      - vendor
      - third_party$
      - builtin$
      - examples$
issues:
  max-issues-per-linter: 0
  max-same-issues: 0
formatters:
  enable:
    - goimports
  settings:
    goimports:
      local-prefixes:
        - github.com/gallyamow/go-fias-exporter
  exclusions:
    generated: lax
    paths:
      - .*_test.go
      - dist
      - vendor
      - third_party$
      - builtin$
      - examples$
